#pragma once

#define ALCO_SENSOR_PORT GPIOB
#define ALCO_SENSOR_PIN GPIO_PIN_0

#define CO2_SENSOR_PORT GPIOB
#define CO2_SENSOR_PIN GPIO_PIN_1

#define FLOOR_SENSOR_PORT GPIOB
#define FLOOR_SENSOR_PIN GPIO_PIN_2

#define FLOOR_UP_PORT GPIOB
#define FLOOR_UP_PIN GPIO_PIN_3

#define FLOOR_DOWN_PORT GPIOB
#define FLOOR_DOWN_PIN GPIO_PIN_4

#define BUZZER_PORT GPIOB
#define BUZZER_PIN GPIO_PIN_5

#define DOOR_PORT GPIOB
#define DOOR_PIN GPIO_PIN_6

#define LOW_HEIGHT_ENDPOINT_PORT GPIOB
#define LOW_HEIGHT_ENDPOINT_PIN GPIO_PIN_7
